### ISSUE TITLE
2bwt-builder for  MacOS

### ISSUE THREAD

**Issue by joey0214** [gigascience/bgi-soap2#1]
Hi,

I'm using a Mac, trying to run SOAP1. However, the mapping index couldn't build for SOAP2. Any executable file of 2bwt-builder for  MacOS? Couldn't find any in executables folder

BTW, I couldn't access to http://soap.genomics.org.cn/ either

Best regards,
Joey

**Comment by pli888** [comment]
I don't remember using 2bwt-builder on MacOS. The 2bwt-builder executable files I have all seem to be Linux-based.

I do not know who maintains  http://soap.genomics.org.cn either so I cannot help with getting the webpage up again.

**Comment by joey0214** [comment]
thanks
